# Generated by Django 5.2.4 on 2025-08-06 07:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('lst_generate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainImageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect_ratio', models.CharField(choices=[('1:1', '1:1'), ('3:2', '3:2'), ('2:3', '2:3'), ('4:3', '4:3'), ('3:4', '3:4'), ('2:1', '2:1'), ('1:2', '1:2')], db_index=True, help_text='画框的宽高比', max_length=10)),
                ('name', models.CharField(help_text="白底图模板的描述性名称, e.g., '3:2/2:1/...'", max_length=255)),
                ('template_image', models.ImageField(help_text='请上传带阴影/光泽等的白底产品图作为模板', upload_to='main_image_templates/')),
                ('target_vertices', models.JSONField(help_text='目标区域八顶点坐标 [x1, y1, x2, y2, x3, y3, x4, y4, x5, y5, x6, y6, x7, y7, x8, y8]')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用此主图模板')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'verbose_name': '主图模板',
                'verbose_name_plural': '主图模板',
            },
        ),
        migrations.CreateModel(
            name='SceneImageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect_ratio', models.CharField(choices=[('1:1', '1:1'), ('3:2', '3:2'), ('2:3', '2:3'), ('4:3', '4:3'), ('3:4', '3:4'), ('2:1', '2:1'), ('1:2', '1:2')], db_index=True, help_text='画框的宽高比', max_length=10)),
                ('name', models.CharField(help_text="模板的描述性名称, e.g., '客厅沙发背景墙-现代风'", max_length=255)),
                ('template_type', models.PositiveSmallIntegerField(default=1, help_text='场景图的展示顺序 (例如 1-5)，数字越小越靠前。', validators=[django.core.validators.MinValueValidator(1)])),
                ('background_image', models.ImageField(help_text='用作背景的场景图片', upload_to='scene_templates/')),
                ('target_vertices', models.JSONField(help_text='目标区域四顶点坐标 [x1, y1, x2, y2, x3, y3, x4, y4]')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用此模板')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
            options={
                'verbose_name': '场景图模板',
                'verbose_name_plural': '场景图模板',
            },
        ),
        migrations.CreateModel(
            name='SynthesizedMainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_image', models.ImageField(upload_to='synthesized_images/main/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('PROCESSING', '处理中'), ('COMPLETED', '已完成'), ('FAILED', '处理失败')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('main_template', models.ForeignKey(help_text='引用了哪个主图模板生成', on_delete=django.db.models.deletion.PROTECT, to='image_synthesis.mainimagetemplate')),
                ('source_listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='synthesized_main_image', to='lst_generate.listing')),
            ],
            options={
                'verbose_name': '合成的主图',
                'verbose_name_plural': '合成的主图',
            },
        ),
        migrations.CreateModel(
            name='SynthesizedSceneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveSmallIntegerField(default=1, help_text='场景图的展示顺序，由模板的template_type决定')),
                ('final_image', models.ImageField(upload_to='synthesized_images/scenes/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('PROCESSING', '处理中'), ('COMPLETED', '已完成'), ('FAILED', '处理失败')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scene_template', models.ForeignKey(help_text='引用了哪个场景图模板生成', on_delete=django.db.models.deletion.PROTECT, to='image_synthesis.sceneimagetemplate')),
                ('source_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synthesized_scene_images', to='lst_generate.listing')),
            ],
            options={
                'verbose_name': '合成的场景图',
                'verbose_name_plural': '合成的场景图',
                'ordering': ['display_order'],
            },
        ),
    ]
