# Generated by Django 5.2.4 on 2025-08-04 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asin', models.CharField(db_index=True, max_length=20, verbose_name='ASIN')),
                ('source', models.CharField(default='amazon_us', help_text='例如: amazon_us, amazon_jp(哪个平台_哪个站点)', max_length=50, verbose_name='数据来源')),
                ('title', models.TextField(blank=True, verbose_name='原始标题')),
                ('bullet_points', models.JSONField(blank=True, default=list, help_text='存储原始的五点描述列表', verbose_name='原始五点')),
                ('review_summary', models.TextField(blank=True, verbose_name='review summary')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_listings', to='core.category', verbose_name='归属类目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_listings', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '原始Listing',
                'verbose_name_plural': '原始Listing',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'asin')},
            },
        ),
    ]
