# Generated by Django 5.2.4 on 2025-08-04 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('keywords_extractor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='用于API交互和内部引用的唯一ID', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='new_title', max_length=255)),
                ('bullet_points', models.JSONField(default=list, help_text='new_bullet_points(JSON)')),
                ('description', models.TextField(blank=True, help_text='new_product_description')),
                ('pattern_image', models.ImageField(help_text='pattern_image', upload_to='patterns/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING_SYNTHESIS', '待图片合成'), ('READY_TO_PUBLISH', '待发布'), ('PUBLISHED', '已发布'), ('ARCHIVED', '已归档')], db_index=True, default='PENDING_SYNTHESIS', help_text='驱动Celery工作流的核心状态字段', max_length=20)),
                ('quality_score', models.IntegerField(blank=True, help_text='Listing质量的AI评分', null=True)),
                ('optimization_suggestions', models.JSONField(blank=True, default=list, help_text='AI提供的优化建议')),
                ('version', models.PositiveIntegerField(default=1, help_text='版本号，用于支持重新生成或A/B测试')),
                ('amazon_asin', models.CharField(blank=True, help_text='成功发布到亚马逊后回填的ASIN', max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='此Listing所属的产品大类，用于驱动图片合成模板选择', on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='core.category')),
                ('keyword_seed', models.ForeignKey(blank=True, help_text='追溯生成此Listing所用的关键词种子', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_listings', to='keywords_extractor.keywordseed')),
                ('user', models.ForeignKey(help_text='数据归属的用户，实现逻辑隔离', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI 生成的 Listing',
                'verbose_name_plural': 'AI 生成的 Listing',
                'db_table': 'ai_listings',
                'ordering': ['-created_at'],
            },
        ),
    ]
