# Generated by Django 5.2.4 on 2025-08-04 08:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordSeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='用于API交互的唯一标识符', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text="为这组关键词起一个易于识别的名称，如 '现代简约风蓝色壁画 - B08H93Z3W5'", max_length=255, verbose_name='种子名称')),
                ('keywords_data', models.JSONField(default=dict, help_text='由AI提取并结构化的JSON数据，包含分类、搜索量等信息', verbose_name='结构化关键词数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, help_text='关联到具体的产品类目，便于分类管理和分析', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='产品类目')),
            ],
            options={
                'verbose_name': '关键词种子',
                'verbose_name_plural': '关键词种子库',
                'ordering': ['-created_at'],
            },
        ),
    ]
