# Generated by Django 5.2.4 on 2025-08-04 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keywords_extractor', '0001_initial'),
        ('scraper', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordseed',
            name='source_raw_listing',
            field=models.ForeignKey(blank=True, help_text='追溯该关键词种子是从哪个原始Listing提取的', null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.rawlisting', verbose_name='来源原始Listing'),
        ),
        migrations.AddField(
            model_name='keywordseed',
            name='user',
            field=models.ForeignKey(help_text='实现用户数据的逻辑隔离', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
    ]
