# Generated by Django 5.2.4 on 2025-08-01 09:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='类目编码', max_length=30, unique=True)),
                ('name', models.CharField(help_text='用于在前端和后台展示给用户的名称', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='取消勾选后，此分类将不会出现在前端下拉选项中')),
            ],
            options={
                'verbose_name': '商品类目',
                'verbose_name_plural': '商品类目',
                'ordering': ['code'],
            },
        ),
    ]
